version: "3.9"

services:
  app:
    build:
      context: .
    volumes:
      - ./backend:/app
    env_file:
      - .env
    ports:
      - "8888:8000"
    restart: on-failure
    command: >
      sh -c "python manage.py wait_db && python manage.py runserver 0.0.0.0:8000"

  db:
    image: mysql:8
    env_file:
      - .env
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3307:3306"
    restart: on-failure

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./client:/usr/share/nginx/html
      - ./backend/static:/usr/share/nginx/doc
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: on-failure

  redis:
    image: redis:alpine

  celery:
    build:
      context: .
    volumes:
      - ./backend:/app
    env_file:
      - .env
    restart: on-failure
    command: >
      sh -c "celery -A configs worker -l info"

# backend:
#    build: .
#    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
#    volumes:
#      - .:/app
#    depends_on:
#      - redis
#    environment:
#      REDIS_URL: redis://redis:6379/0  # Доступ до Redis з контейнера
#
#  # Celery worker
#  celery:
#    build: .
#    command: celery -A app.celery_app worker --loglevel=info
#    depends_on:
#      - redis
#    environment:
#      - REDIS_URL=redis://redis:6379/0
#    volumes:
#      - .:/app